// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package domain

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockTaskRepository creates a new instance of MockTaskRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTaskRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTaskRepository {
	mock := &MockTaskRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTaskRepository is an autogenerated mock type for the TaskRepository type
type MockTaskRepository struct {
	mock.Mock
}

type MockTaskRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTaskRepository) EXPECT() *MockTaskRepository_Expecter {
	return &MockTaskRepository_Expecter{mock: &_m.Mock}
}

// CreateTask provides a mock function for the type MockTaskRepository
func (_mock *MockTaskRepository) CreateTask(task Task) error {
	ret := _mock.Called(task)

	if len(ret) == 0 {
		panic("no return value specified for CreateTask")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(Task) error); ok {
		r0 = returnFunc(task)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTaskRepository_CreateTask_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateTask'
type MockTaskRepository_CreateTask_Call struct {
	*mock.Call
}

// CreateTask is a helper method to define mock.On call
//   - task Task
func (_e *MockTaskRepository_Expecter) CreateTask(task interface{}) *MockTaskRepository_CreateTask_Call {
	return &MockTaskRepository_CreateTask_Call{Call: _e.mock.On("CreateTask", task)}
}

func (_c *MockTaskRepository_CreateTask_Call) Run(run func(task Task)) *MockTaskRepository_CreateTask_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 Task
		if args[0] != nil {
			arg0 = args[0].(Task)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTaskRepository_CreateTask_Call) Return(err error) *MockTaskRepository_CreateTask_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTaskRepository_CreateTask_Call) RunAndReturn(run func(task Task) error) *MockTaskRepository_CreateTask_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteTask provides a mock function for the type MockTaskRepository
func (_mock *MockTaskRepository) DeleteTask(taskId int64) error {
	ret := _mock.Called(taskId)

	if len(ret) == 0 {
		panic("no return value specified for DeleteTask")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(int64) error); ok {
		r0 = returnFunc(taskId)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTaskRepository_DeleteTask_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteTask'
type MockTaskRepository_DeleteTask_Call struct {
	*mock.Call
}

// DeleteTask is a helper method to define mock.On call
//   - taskId int64
func (_e *MockTaskRepository_Expecter) DeleteTask(taskId interface{}) *MockTaskRepository_DeleteTask_Call {
	return &MockTaskRepository_DeleteTask_Call{Call: _e.mock.On("DeleteTask", taskId)}
}

func (_c *MockTaskRepository_DeleteTask_Call) Run(run func(taskId int64)) *MockTaskRepository_DeleteTask_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int64
		if args[0] != nil {
			arg0 = args[0].(int64)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTaskRepository_DeleteTask_Call) Return(err error) *MockTaskRepository_DeleteTask_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTaskRepository_DeleteTask_Call) RunAndReturn(run func(taskId int64) error) *MockTaskRepository_DeleteTask_Call {
	_c.Call.Return(run)
	return _c
}

// GetSubtasks provides a mock function for the type MockTaskRepository
func (_mock *MockTaskRepository) GetSubtasks(taskId int64) ([]Task, error) {
	ret := _mock.Called(taskId)

	if len(ret) == 0 {
		panic("no return value specified for GetSubtasks")
	}

	var r0 []Task
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(int64) ([]Task, error)); ok {
		return returnFunc(taskId)
	}
	if returnFunc, ok := ret.Get(0).(func(int64) []Task); ok {
		r0 = returnFunc(taskId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]Task)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(int64) error); ok {
		r1 = returnFunc(taskId)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTaskRepository_GetSubtasks_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSubtasks'
type MockTaskRepository_GetSubtasks_Call struct {
	*mock.Call
}

// GetSubtasks is a helper method to define mock.On call
//   - taskId int64
func (_e *MockTaskRepository_Expecter) GetSubtasks(taskId interface{}) *MockTaskRepository_GetSubtasks_Call {
	return &MockTaskRepository_GetSubtasks_Call{Call: _e.mock.On("GetSubtasks", taskId)}
}

func (_c *MockTaskRepository_GetSubtasks_Call) Run(run func(taskId int64)) *MockTaskRepository_GetSubtasks_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int64
		if args[0] != nil {
			arg0 = args[0].(int64)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTaskRepository_GetSubtasks_Call) Return(tasks []Task, err error) *MockTaskRepository_GetSubtasks_Call {
	_c.Call.Return(tasks, err)
	return _c
}

func (_c *MockTaskRepository_GetSubtasks_Call) RunAndReturn(run func(taskId int64) ([]Task, error)) *MockTaskRepository_GetSubtasks_Call {
	_c.Call.Return(run)
	return _c
}

// GetTaskById provides a mock function for the type MockTaskRepository
func (_mock *MockTaskRepository) GetTaskById(taskId int64) (Task, error) {
	ret := _mock.Called(taskId)

	if len(ret) == 0 {
		panic("no return value specified for GetTaskById")
	}

	var r0 Task
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(int64) (Task, error)); ok {
		return returnFunc(taskId)
	}
	if returnFunc, ok := ret.Get(0).(func(int64) Task); ok {
		r0 = returnFunc(taskId)
	} else {
		r0 = ret.Get(0).(Task)
	}
	if returnFunc, ok := ret.Get(1).(func(int64) error); ok {
		r1 = returnFunc(taskId)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTaskRepository_GetTaskById_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTaskById'
type MockTaskRepository_GetTaskById_Call struct {
	*mock.Call
}

// GetTaskById is a helper method to define mock.On call
//   - taskId int64
func (_e *MockTaskRepository_Expecter) GetTaskById(taskId interface{}) *MockTaskRepository_GetTaskById_Call {
	return &MockTaskRepository_GetTaskById_Call{Call: _e.mock.On("GetTaskById", taskId)}
}

func (_c *MockTaskRepository_GetTaskById_Call) Run(run func(taskId int64)) *MockTaskRepository_GetTaskById_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int64
		if args[0] != nil {
			arg0 = args[0].(int64)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTaskRepository_GetTaskById_Call) Return(task Task, err error) *MockTaskRepository_GetTaskById_Call {
	_c.Call.Return(task, err)
	return _c
}

func (_c *MockTaskRepository_GetTaskById_Call) RunAndReturn(run func(taskId int64) (Task, error)) *MockTaskRepository_GetTaskById_Call {
	_c.Call.Return(run)
	return _c
}

// GetTasks provides a mock function for the type MockTaskRepository
func (_mock *MockTaskRepository) GetTasks() ([]Task, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetTasks")
	}

	var r0 []Task
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() ([]Task, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() []Task); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]Task)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTaskRepository_GetTasks_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTasks'
type MockTaskRepository_GetTasks_Call struct {
	*mock.Call
}

// GetTasks is a helper method to define mock.On call
func (_e *MockTaskRepository_Expecter) GetTasks() *MockTaskRepository_GetTasks_Call {
	return &MockTaskRepository_GetTasks_Call{Call: _e.mock.On("GetTasks")}
}

func (_c *MockTaskRepository_GetTasks_Call) Run(run func()) *MockTaskRepository_GetTasks_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTaskRepository_GetTasks_Call) Return(tasks []Task, err error) *MockTaskRepository_GetTasks_Call {
	_c.Call.Return(tasks, err)
	return _c
}

func (_c *MockTaskRepository_GetTasks_Call) RunAndReturn(run func() ([]Task, error)) *MockTaskRepository_GetTasks_Call {
	_c.Call.Return(run)
	return _c
}

// PatchTask provides a mock function for the type MockTaskRepository
func (_mock *MockTaskRepository) PatchTask(taskId int64, data Task) error {
	ret := _mock.Called(taskId, data)

	if len(ret) == 0 {
		panic("no return value specified for PatchTask")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(int64, Task) error); ok {
		r0 = returnFunc(taskId, data)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTaskRepository_PatchTask_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PatchTask'
type MockTaskRepository_PatchTask_Call struct {
	*mock.Call
}

// PatchTask is a helper method to define mock.On call
//   - taskId int64
//   - data Task
func (_e *MockTaskRepository_Expecter) PatchTask(taskId interface{}, data interface{}) *MockTaskRepository_PatchTask_Call {
	return &MockTaskRepository_PatchTask_Call{Call: _e.mock.On("PatchTask", taskId, data)}
}

func (_c *MockTaskRepository_PatchTask_Call) Run(run func(taskId int64, data Task)) *MockTaskRepository_PatchTask_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int64
		if args[0] != nil {
			arg0 = args[0].(int64)
		}
		var arg1 Task
		if args[1] != nil {
			arg1 = args[1].(Task)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTaskRepository_PatchTask_Call) Return(err error) *MockTaskRepository_PatchTask_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTaskRepository_PatchTask_Call) RunAndReturn(run func(taskId int64, data Task) error) *MockTaskRepository_PatchTask_Call {
	_c.Call.Return(run)
	return _c
}
